### ISSUE TITLE
0.6.5版本向下兼容性问题

### ISSUE THREAD

**Issue by mikualpha** [lawvs/poi-plugin-quest-2#12]
**poi 版本 / poi version:** 10.6.0

**操作系统 / OS:** Windows 10 20H2

**插件版本 / Plugin version:** 0.6.5

**你遇到了什么样的问题 / The problem you've met:** [这个提交](https://github.com/lawvs/poi-plugin-quest-2/commit/15962e25456861c4f3c7ec41a9bd5d5ab2196680)似乎导致了低级版本的兼容性问题？

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
```
SyntaxError: C:\Users\USERNAME\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\patch.ts: Unexpected token, expected "," (46:11)

  44 |     Object.entries(data).map(
  45 |       ([apiNo, { code, desc, memo2 }]: [
> 46 |         key: string,
     |            ^
  47 |         value: { code: string; desc: string; memo2?: string }
  48 |       ]) => [
  49 |         apiNo,
    at Object._raise (D:\poi\resources\app.asar\node_modules\@babel\parser\src\parser\location.js:241:45)
    at Object.raiseWithData (D:\poi\resources\app.asar\node_modules\@babel\parser\src\parser\location.js:236:17)
    at Object.raise (D:\poi\resources\app.asar\node_modules\@babel\parser\src\parser\location.js:220:17)
    at Object.unexpected (D:\poi\resources\app.asar\node_modules\@babel\parser\src\parser\util.js:149:16)
    at Object.expect (D:\poi\resources\app.asar\node_modules\@babel\parser\src\parser\util.js:129:28)
    at Object.tsParseDelimitedListWorker (D:\poi\resources\app.asar\node_modules\@babel\parser\src\plugins\typescript\index.js:265:16)
```

**Comment by mikualpha** [comment]
0.6.7版本验证正常了，感谢修复0w0
