### ISSUE TITLE
Fix type check

### ISSUE THREAD

**Issue by lawvs** [lawvs/poi-plugin-quest-2#15]
Revert https://github.com/lawvs/poi-plugin-quest-2/pull/14/commits/98dfd70f7efcd53f76dba2101a7c406675abc5aa

```
> poi-plugin-quest-info-2@0.8.0 typeCheck
> tsc --noEmit

node_modules/micro-memoize/src/Cache.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { MicroMemoize } from './types';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/micro-memoize/src/utils.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { Dictionary, MicroMemoize } from './types';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/micro-memoize/src/Cache.ts:1
     1  node_modules/micro-memoize/src/utils.ts:1
```

**Comment by BloodyJace** [comment]
I'm not quite sure what happened I am an amateur, and this is the only place that I found to report the error.

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:48)
    at Object.enqueueSetState (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at Text.C.setState (C:\Program Files\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at Text.update (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:60:14)
    at Text.componentDidUpdate (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:40:14)
    at Yi (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:502)
    at dk (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:259:160)
    at exports.unstable_runWithPriority (C:\Program Files\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Uj (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:252:279)
    at Lj (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:371)
    at C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (C:\Program Files\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Oh (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:408)
    at listener (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\hooks.ts:45:32)
    at handleChange (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\store.ts:26:7)
    at dispatch (C:\Program Files\poi\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at C:\Program Files\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at parseResponses (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:101:5)
    at resolveResponses (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:126:7)
    at handleProxyGameOnResponse (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:141:7)
    at CallbacksRegistry.apply (C:\Program Files\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54:29)
    at C:\Program Files\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345:23
    at EventEmitter.<anonymous> (C:\Program Files\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327:13)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:73:1017)


    at Text (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:28:47)
    at span
    at Tag (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\tag\tag.js:30:47)
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at span
    at ResizeSensor (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at InnerReference (C:\Program Files\poi\resources\app.asar\node_modules\react-popper\lib\cjs\Reference.js:40:35)
    at Reference
    at span
    at Manager (C:\Program Files\poi\resources\app.asar\node_modules\react-popper\lib\cjs\Manager.js:39:35)
    at Popover (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\popover\popover.js:45:47)
    at Tooltip (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\tooltip\tooltip.js:31:47)
    at C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestTag.tsx:39:3
    at QuestTag (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestTag.tsx:68:3)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at CardAction (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:31:3)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at Card (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:47:3
    at div
    at CellMeasurer (C:\Program Files\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\CellMeasurer\CellMeasurer.js:51:37)
    at div
    at div
    at Grid (C:\Program Files\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\Grid\Grid.js:93:37)
    at List (C:\Program Files\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\List\List.js:50:37)
    at div
    at AutoSizer (C:\Program Files\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\AutoSizer\AutoSizer.js:48:37)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at QuestList (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestList.tsx:79:3)
    at Main (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\App.tsx:39:39)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at StoreProvider (C:\Users\USER\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\store\store.tsx:73:3)
    at App
    at div
    at Card (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (C:\Program Files\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (C:\Program Files\poi\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (C:\Program Files\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (C:\Program Files\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (C:\Program Files\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (C:\Program Files\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)
